apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: market-siparis
  labels:
    app.kubernetes.io/name: market-minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
