apiVersion: v1
kind: Secret
metadata:
  name: market-secrets
  namespace: market-siparis
  labels:
    app.kubernetes.io/name: market-siparis
type: Opaque
# UYARI: Prod ortamda SealedSecrets veya External Secrets Operator kullanin.
stringData:
  SPRING_DATASOURCE_USERNAME: "market_user"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION_USE_MIN_256_BIT_KEY"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "CHANGE_ME_IN_PRODUCTION"
