apiVersion: v1
kind: Secret
metadata:
  name: market-backend-secret
  namespace: market-siparis
  labels:
    app.kubernetes.io/name: market-siparis
type: Opaque
# UYARI: Prod ortamda SealedSecrets veya External Secrets Operator kullanin.
stringData:
  SPRING_DATASOURCE_USERNAME: "market_user"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET: "*VIOEi/_Db-N]m(X@w6up*lY9h&kp84qQF7oPsy:GF?"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "CHANGE_ME_IN_PRODUCTION"
  SMS_VATAN_API_ID: "e191960a19f7b3bf65d76e62"
  SMS_VATAN_API_KEY: "86eec7f22eb3ca8c39a37d3c"
